name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Restore CI Cache
        id: cache-restore
        uses: actions/cache@v2.1.4
        with:
          path: node_modules
          key: ${{ runner.os }}-14-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: npm ci
      - name: Run Tests
        run: npm run test

  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Restore CI Cache
        id: cache-restore
        uses: actions/cache@v2.1.4
        with:
          path: node_modules
          key: ${{ runner.os }}-14-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: npm ci
      - name: Run Build
        run: npm run build
